CREATE TABLE tbl_boss(
	bossId VARCHAR2(15),
	bName VARCHAR2(15) NOT NULL,
	bNickname VARCHAR2(20) UNIQUE NOT NULL,
	bPassword VARCHAR2(30) NOT NULL,
	bBirth DATE,
	bPostnumber VARCHAR2(10) NOT NULL,
	bAddress VARCHAR2(200) NOT NULL,
	bdetailAddress VARCHAR2(100) NOT NULL,
	bPhone VARCHAR2(15) UNIQUE NOT NULL,
	bEmail VARCHAR2(50) UNIQUE NOT NULL,
	bSigndate DATE DEFAULT SYSDATE,
	
	CONSTRAINT pk_boss_bossId PRIMARY KEY(bossId)
)

 SELECT * FROM tbl_boss